import { readFileSync, existsSync } from "node:fs";
import path from "node:path";

interface ClaudeHookInput {
  tool_input?: {
    file_path?: string;
  };
}

const input = JSON.parse(readFileSync(0, "utf8")) as ClaudeHookInput;
const filePath = input.tool_input?.file_path;

if (!filePath) {
  process.exit(0);
}

const protectedPaths = [
  "public/map.js",
  "public/turbo.js",
  "public/output.css",
  "output/licenses.json",
  "output/licenses.db",
];
const protectedConfigs = [".oxlintrc.json", ".oxfmtrc.json", "lefthook.yml", "tsconfig.json"];

const baseName = path.basename(filePath);

if (protectedConfigs.includes(baseName) || protectedPaths.some((p) => filePath.endsWith(p))) {
  console.log(
    JSON.stringify({
      hookSpecificOutput: {
        hookEventName: "PreToolUse",
        permissionDecision: "deny",
        permissionDecisionReason: `Editing ${baseName} is blocked by policy. This file is generated or protected.`,
      },
    }),
  );
  process.exit(0);
}

if (existsSync(filePath)) {
  const currentContents = readFileSync(filePath, "utf8");
  if (/autogenerated/iu.test(currentContents.slice(0, 200))) {
    console.log(
      JSON.stringify({
        hookSpecificOutput: {
          hookEventName: "PreToolUse",
          permissionDecision: "deny",
          permissionDecisionReason: "Files marked as autogenerated must not be edited.",
        },
      }),
    );
    process.exit(0);
  }
}
